name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PRODUCTION_SERVER_PORT }} ${{ secrets.PRODUCTION_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure target theme directory exists on remote
        run: |
          SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
          SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
          SSH_PORT="${{ secrets.PRODUCTION_SERVER_PORT }}"
          THEME_PATH="${{ secrets.PRODUCTION_THEME_PATH }}"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p "${SSH_PORT}" "${SSH_USER}"@"${SSH_HOST}" "mkdir -p \"${THEME_PATH}\""

      - name: Rsync theme files to PRODUCTION
        run: |
          SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
          SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
          SSH_PORT="${{ secrets.PRODUCTION_SERVER_PORT }}"
          THEME_PATH="${{ secrets.PRODUCTION_THEME_PATH }}"
          rsync -avzc --delete --exclude='.*' --exclude README.md \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${SSH_PORT}" \
            ./ "${SSH_USER}"@"${SSH_HOST}":"${THEME_PATH}"

      - name: Clear WordPress Cache
        run: |
          SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
          SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
          SSH_PORT="${{ secrets.PRODUCTION_SERVER_PORT }}"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p "${SSH_PORT}" "${SSH_USER}"@"${SSH_HOST}" "wp cache flush"

  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
