name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PORT: ${{ secrets.PRODUCTION_SERVER_PORT }}
          SSH_HOST: ${{ secrets.PRODUCTION_SERVER_HOST }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Ensure target theme directory exists on remote
        run: |
          SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
          SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
          SSH_PORT="${{ secrets.PRODUCTION_SERVER_PORT }}"
          THEME_PATH="${{ secrets.PRODUCTION_THEME_PATH }}"
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p "${SSH_PORT}" "${SSH_USER}"@"${SSH_HOST}" "mkdir -p \"${THEME_PATH}\""

      - name: Rsync theme files to PRODUCTION
        run: |
          SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
          SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
          SSH_PORT="${{ secrets.PRODUCTION_SERVER_PORT }}"
          THEME_PATH="${{ secrets.PRODUCTION_THEME_PATH }}"
          rsync -avzc --delete --exclude='.*' --exclude README.md \
            -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p ${SSH_PORT}" \
            ./ "${SSH_USER}"@"${SSH_HOST}":"${THEME_PATH}"

      - name: Clear WordPress Cache
        run: |
          SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
          SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
          SSH_PORT="${{ secrets.PRODUCTION_SERVER_PORT }}"
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p "${SSH_PORT}" "${SSH_USER}"@"${SSH_HOST}" "wp cache flush"
